### ISSUE TITLE
Compilation error and warnings

### ISSUE THREAD

**Issue by iadnan** [HussainShabbir/Vehicle-Management#1]
/Users/ibrahimadnan/Downloads/Vehicle-Management-master/ModelController/VehicleManagementModelController.swift:50:90: '++' is deprecated: it will be removed in Swift 3
/Users/ibrahimadnan/Downloads/Vehicle-Management-master/ModelController/VehicleManagementModelController.swift:50:13: C-style for statement is deprecated and will be removed in a future version of Swift
/Users/ibrahimadnan/Downloads/Vehicle-Management-master/ModelController/VehicleManagementModelController.swift:60:89: '++' is deprecated: it will be removed in Swift 3
/Users/ibrahimadnan/Downloads/Vehicle-Management-master/ModelController/VehicleManagementModelController.swift:60:13: C-style for statement is deprecated and will be removed in a future version of Swift
(null): error: /Desktop/car.jpg: No such file or directory
(null): error: /Desktop/bike.jpeg: No such file or directory

**Comment by iadnan** [comment]
in VehicleManagementModelControlleryou are using for (var index = 0; index < self.dataModelOfFourWheeler.dataList.count; index++) . Why not use " for model in self.dataModelOfFourWheeler.dataList"

**Comment by iadnan** [comment]
I am not sure you have created a correct model structure. There a dataList array in GroupModel which stores object of GroupModel. Why is it done this way ?

why didn't you create just var dataList : [GroupModel] in VehicleManagementModelController

**Comment by HussainShabbir** [comment]
Hi Adnan,
Thanks for your comment.
I have fixed the two image file and have updated my comments below:-

1) in VehicleManagementModelControlleryou are using for (var index = 0; index < self.dataModelOfFourWheeler.dataList.count; index++) . Why not use " for model in self.dataModelOfFourWheeler.dataList"

The reason why I am using here is I needed the index for removing the object as well. So for that I have not used " for model in self.dataModelOfFourWheeler.dataList". Please let me know if you have any good advice to resolve this.

2) I am not sure you have created a correct model structure. There a dataList array in GroupModel which stores object of GroupModel. Why is it done this way ?

why didn't you create just var dataList : [GroupModel] in VehicleManagementModelController

This is the NSOutlineView data structure which needs to have data in tree format for eg. @["name" : "Xyz", "ChildArray" : "xyz"]; So for that reason, I have defined the model and inside that I have used the  dataList array which contains the child object. This is not possible to declare in VehicleManagementModelController. If I do that, then tree structure will not work and It will not display any data.

**Comment by HussainShabbir** [comment]
Hi Adnan,

Please ignore my comments on 2. Point. Your suggestion was correct. Also I have modified the For loop in Swift style as well.
